// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/scale-health-hub/Current.tsx": () => import("../components/mockups/scale-health-hub/Current.tsx"),
  "./components/mockups/scale-health-hub/ExclusiveMarketplace.tsx": () => import("../components/mockups/scale-health-hub/ExclusiveMarketplace.tsx")
};
